Cypress.Commands.add('fillRegistrationForm', (user) => {

    // fill in the data
    cy.get('#personalSalutation').select(1)
    cy.get('#personalFirstName').click()
        .should('be.empty')
        .type(user.firstName)
    cy.get('#personalLastName').click()
        .should('be.empty')
        .type(user.lastName)
    cy.get('#personalPassword').click()
        .should('be.empty')
        .type(user.password)
    cy.get('#personalMail').click()
        .should('be.empty')
        .type(user.email)
    cy.get('#billingAddressAddressStreet').click({force: true})
        .should('be.empty')
        .type(user.street)
    cy.get('#billingAddressAddressZipcode').click()
        .should('be.empty')
        .type(user.zipcode)
    cy.get('#billingAddressAddressCity').click()
        .should('be.empty')
        .type(user.city)
    cy.get('#billingAddressAddressCountry').select(1)
    cy.get('#billingAddressAddressCountryState').select(1)
})
